# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IDNSRecommender.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(653, 747)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.checkBox_Newcustomer = QtGui.QCheckBox(Dialog)
        self.checkBox_Newcustomer.setGeometry(QtCore.QRect(20, 90, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Newcustomer.setFont(font)
        self.checkBox_Newcustomer.setObjectName(_fromUtf8("checkBox_Newcustomer"))
        self.text_Name = QtGui.QTextEdit(Dialog)
        self.text_Name.setGeometry(QtCore.QRect(80, 120, 361, 31))
        self.text_Name.setObjectName(_fromUtf8("text_Name"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 53, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(450, 120, 53, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(240, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.textType = QtGui.QTextEdit(Dialog)
        self.textType.setGeometry(QtCore.QRect(130, 170, 471, 31))
        self.textType.setObjectName(_fromUtf8("textType"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 300, 591, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 420, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 480, 581, 261))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 440, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.textItems = QtGui.QTextEdit(Dialog)
        self.textItems.setGeometry(QtCore.QRect(10, 370, 591, 31))
        self.textItems.setObjectName(_fromUtf8("textItems"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 330, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.btLoad = QtGui.QPushButton(Dialog)
        self.btLoad.setGeometry(QtCore.QRect(510, 220, 93, 28))
        self.btLoad.setObjectName(_fromUtf8("btLoad"))
        self.lnID = QtGui.QLineEdit(Dialog)
        self.lnID.setGeometry(QtCore.QRect(490, 120, 111, 31))
        self.lnID.setObjectName(_fromUtf8("lnID"))
        self.btRecom = QtGui.QPushButton(Dialog)
        self.btRecom.setGeometry(QtCore.QRect(250, 400, 93, 28))
        self.btRecom.setObjectName(_fromUtf8("btRecom"))
        self.lbPurchase = QtGui.QLabel(Dialog)
        self.lbPurchase.setGeometry(QtCore.QRect(170, 270, 371, 16))
        self.lbPurchase.setText(_fromUtf8(""))
        self.lbPurchase.setObjectName(_fromUtf8("lbPurchase"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Customer Details", None))
        self.checkBox_Newcustomer.setText(_translate("Dialog", "New Customer", None))
        self.label_2.setText(_translate("Dialog", "Name", None))
        self.label_3.setText(_translate("Dialog", "ID", None))
        self.label_4.setText(_translate("Dialog", "Item Suggestions", None))
        self.label_5.setText(_translate("Dialog", "Company Type", None))
        self.label_6.setText(_translate("Dialog", "Past Purchases", None))
        self.label_7.setText(_translate("Dialog", "Item Suggestions", None))
        self.label_8.setText(_translate("Dialog", "Customer might be interested in these products with these price ranges: ", None))
        self.label_9.setText(_translate("Dialog", "Querried item", None))
        self.btLoad.setText(_translate("Dialog", "Load", None))
        self.btRecom.setText(_translate("Dialog", "Recommend", None))

